### PR TITLE
[LAPACK][cuSOLVER] Get cuSOLVER backend to build with SYCL2020 changes

### LINKED ISSUE #360: oneMKL build failed with the latest syclos compiler
# Summary
oneMKL build failed with the latest syclos compiler (20230731)

# Steps to reproduce
```
cmake .. \
         -DENABLE_CUBLAS_BACKEND=True    \
         -DENABLE_CUSOLVER_BACKEND=True  \
         -DENABLE_CURAND_BACKEND=True    \
         -DENABLE_CUFFT_BACKEND=True     \
         -DENABLE_MKLCPU_BACKEND=False   \
         -DENABLE_MKLGPU_BACKEND=False   \
         -DBUILD_FUNCTIONAL_TESTS=False  \
         -DCMAKE_INSTALL_PREFIX=/export/users/zhiweij1/workspace/onemkl_interfaces/20230801

make -j12 && make install
```

# Observed behavior
Error message
```
In file included from /export/users/zhiweij1/workspace/onemkl_interfaces/oneMKL/src/lapack/backends/cusolver/cusolver_batch.cpp:21:
In file included from /export/users/zhiweij1/workspace/onemkl_interfaces/oneMKL/src/lapack/backends/cusolver/cusolver_task.hpp:32:
In file included from /export/users/zhiweij1/workspace/onemkl_interfaces/oneMKL/src/lapack/backends/cusolver/cusolver_scope_handle.hpp:27:
/nfs/shm/proj/icl/cmplrarch/deploy_syclos/llorgsyclngefi2linux/20230731_160000/build/linux_qa_release/bin/../include/sycl/backend/cuda.hpp:17:2: warning: sycl/backend/cuda.hpp is deprecated and not required anymore [-W#warnings]
   17 | #warning sycl/backend/cuda.hpp is deprecated and not required anymore
      |  ^
In file included from /export/users/zhiweij1/workspace/onemkl_interfaces/oneMKL/src/lapack/backends/cusolver/cusolver_batch.cpp:21:
In file included from /export/users/zhiweij1/workspace/onemkl_interfaces/oneMKL/src/lapack/backends/cusolver/cusolver_task.hpp:32:
/export/users/zhiweij1/workspace/onemkl_interfaces/oneMKL/src/lapack/backends/cusolver/cusolver_scope_handle.hpp:82:11: error: no type named 'interop_handler' in namespace 'sycl'; did you mean 'interop_handle'?
   82 |     sycl::interop_handler &ih;
      |     ~~~~~~^~~~~~~~~~~~~~~
      |           interop_handle
/nfs/shm/proj/icl/cmplrarch/deploy_syclos/llorgsyclngefi2linux/20230731_160000/build/linux_qa_release/bin/../include/sycl/interop_handle.hpp:36:7: note: 'interop_handle' declared here
   36 | class interop_handle {
      |       ^
```

I think oneMKL needs to update the code since the compiler has merged some ABI-breaking PRs (e.g., https://github.com/intel/llvm/pull/10246/)

### PR DESCRIPTION
**Pull request by sknepper**
# Description

Allows oneMKL to build with cuSolver backend and fixes the many resulting segfaults/failures. The only remaining test failures are in sytrd/hetrd, which are due to a failing off-diagonal check. This may be an issue in the underlying cuSOLVER library.

Changes include:
    interop_handler -> interop_handle
    get_* -> get_native_*
    backend::cuda -> backend::ext_oneapi_cuda
    Also applied same fix for performance as in #169
    Remove SYCL2020_DISABLE_DEPRECATION_WARNINGS flag for cuSOLVER backend
    Wait on the queue for each scratchpad_size function

Fixes #360 

# Checklist

## All Submissions

- [No ] Do all unit tests pass locally? Attach a log. [cusolver.txt](https://github.com/oneapi-src/oneMKL/files/12756326/cusolver.txt)
However, only sytrd/hetrd are failing due to an off-diagonal check.
- [Yes ] Have you formatted the code using clang-format?

### CODE REVIEW

File: src/lapack/backends/cusolver/cusolver_scope_handle.hpp [hunk 1]
```diff
@@ -23,8 +23,10 @@
 #else
 #include <CL/sycl.hpp>
 #endif
-#if __has_include(<sycl/backend/cuda.hpp>)
+#if __has_include(<sycl/context.hpp>)
+#if __SYCL_COMPILER_VERSION <= 20220930
 #include <sycl/backend/cuda.hpp>
```
Comment (jadurazo) [inline src/lapack/backends/cusolver/cusolver_scope_handle.hpp:28]: Just checking if we need to have a `has_include` macro for this include file? (It was removed in line 26 above.)

**Review by jadurazo — APPROVED** [review]
Looks good! Just one question.

File: src/lapack/backends/cusolver/cusolver_scope_handle.hpp (hunk 1 above)
Comment (sknepper) [reply src/lapack/backends/cusolver/cusolver_scope_handle.hpp:28]: Good question! I followed the same changes that had been made to the src/blas/backends/cublas/cublas_scope_handle.hpp file, so we're aligned with the cuBLAS backend.

My understanding is that the location of some of the headers changed based on the compiler version. If there is an overarching CL directory, that's one case. And we can capture that case by checking the existence of sycl/context.hpp (without the CL/ directory), so I don't think we need to verify that sycl/backend/cuda.hpp exists.
If there's not a CL/ directory, then we look at the date of the compiler. Based on #295 , it looks like there were deprecation warnings for the cuda.hpp file, so that's why it's only conditionally included.

File: src/lapack/backends/cusolver/cusolver_scope_handle.cpp [hunk 2]
```diff
@@ -39,12 +39,12 @@ thread_local cusolver_handle<pi_context> CusolverScopedContextHandler::handle_he
     cusolver_handle<pi_context>{};
 
 CusolverScopedContextHandler::CusolverScopedContextHandler(sycl::queue queue,
-                                                           sycl::interop_handler &ih)
+                                                           sycl::interop_handle &ih)
         : ih(ih),
           needToRecover_(false) {
-    placedContext_ = queue.get_context();
+    placedContext_ = new sycl::context(queue.get_context());
```
Comment (ericlars) [inline src/lapack/backends/cusolver/cusolver_scope_handle.cpp:45]: Is there a reason placedContext was changed to a pointer? There is a very contrived scenario where a memory leak could occur. The cuda context get/set functions can throw and the user could recover from the exception, but placedContext_ will have leaked.

Comment (sknepper) [reply src/lapack/backends/cusolver/cusolver_scope_handle.cpp:45]: Thanks for the question! This was done for performance reasons, following the same fix as in https://github.com/oneapi-src/oneMKL/pull/169. According to the description for the PR, it took a long time to create sycl::context with default constructor in cublas handler. I didn't run any performance tests, but I don't see a reason it would be different for the cuSOLVER backend. In #106 , you can see some performance comparisons for sgemm. The change significantly improved the performance of the oneMKL interfaces with cuBLAS backend.

Comment (ericlars) [reply src/lapack/backends/cusolver/cusolver_scope_handle.cpp:45]: It does eliminate a call to the default constructor. I don't see how failing to get/set the cuda context would be recoverable anyways so I'll approve this as is.

**Review by ericlars — APPROVED** [review]
