### PR TITLE
[BLAS] Fix symbol conflicts between backends and reference

### LINKED ISSUE #204: BLAS: tests may not be executing the right backend
# Summary
When trying a new library we encountered an unexpected behaviour, as it seems that for BLAS (at least), most tests are actually comparing the reference libblas to itself (but wrapped in sycl), not to the actual intended backend. This can be reproduced with MKL.

As I understand, unit_tests such as axpy_usm.cpp are compiled and linked with reference libblas, hence cblas_xxx symbols are already resolved at the start of execution.

When the test ( for example RT test AxpyUsmTestSuite/AxpyUsmTests.RealSinglePrecision/Column_Major_SYCL_host_device ) is executed, it runs the reference call, and then tries the sycl backend tested (mklcpu for example), by dlopening the corresponding libonemkl_blas_mklcpu.so lib. But as this dlopen is made lazily and not deeply, the cblas_saxpy symbol still remains the one from libcblas. This is for the RT variant of the test, as the CT variant does not dynamically load anything, so the problem is worse for these.

gdb trace, with breaks on cblas_saxpy and dlopen

gdb --args ./bin/test_main_blas_rt "--gtest_filter=AxpyUsmTestSuite/AxpyUsmTests.RealSinglePrecision/Column_Major_SYCL_host_device" "--gtest_also_run_disabled_tests"

first breakpoint is the reference call, 2 is the dlopen and 3 is the call which should be from the mkl :

```
[ RUN      ] AxpyUsmTestSuite/AxpyUsmTests.RealSinglePrecision/Column_Major_SYCL_host_device

Breakpoint 1, 0x00007ffff7f9cdd0 in cblas_saxpy () from /foo/lapack/build/lib/libcblas.so.3
(gdb)
Continuing.

Breakpoint 2, ___dlopen (file=0x7ffff7f0c020 "libonemkl_blas_mklcpu.so", mode=257) at ./dlfcn/dlopen.c:77
77      in ./dlfcn/dlopen.c
(gdb) c
Continuing.
[New Thread 0x7fffe79ff640 (LWP 19332)]
[Switching to Thread 0x7fffe79ff640 (LWP 19332)]

Thread 2 "test_main_blas_" hit Breakpoint 1, 0x00007ffff7f9cdd0 in cblas_saxpy () from /foo/lapack/build/lib/libcblas.so.3
(gdb) bt
#0  0x00007ffff7f9cdd0 in cblas_saxpy () from /foo/lapack/build/lib/libcblas.so.3
#1  0x00007ffff7d0f741 in cl::sycl::detail::DispatchHostTask::operator()() const () from /foo/llvm/build/lib/libsycl.so.5
#2  0x00007ffff7c79ae3 in cl::sycl::detail::ThreadPool::worker() () from /foo/llvm/build/lib/libsycl.so.5

```

We can see that the third breakpoint, with the call from within the sycl host task seems to be inside libcblas and not the mkl one.

The behavior of the dlopen can be altered by using RTLD_DEEPBIND instead, to force overriding previously loaded symbols with the new ones, and this seems to make the test work as expected

so adding | RTLD_DEEPBIND at https://github.com/oneapi-src/oneMKL/blob/develop/src/include/function_table_initializer.hpp#L34 yields a different and more expected results (even if using it may change too much the behaviour for actual codes)

```
[ RUN      ] AxpyUsmTestSuite/AxpyUsmTests.RealSinglePrecision/Column_Major_SYCL_host_device

Breakpoint 2, 0x00007ffff7f9cdd0 in cblas_saxpy () from /foo/lapack/build/lib/libcblas.so.3
(gdb)
Continuing.

Breakpoint 1, ___dlopen (file=0x7ffff7f0c020 "libonemkl_blas_mklcpu.so", mode=265) at ./dlfcn/dlopen.c:77
77      in ./dlfcn/dlopen.c
(gdb)
Continuing.
[New Thread 0x7fffe79ff640 (LWP 20195)]
[Switching to Thread 0x7fffe79ff640 (LWP 20195)]

Thread 2 "test_main_blas_" hit Breakpoint 2, 0x00007fffee720f00 in cblas_saxpy () from /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_ilp64.so.2
(gdb) bt
#0  0x00007fffee720f00 in cblas_saxpy () from /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_ilp64.so.2
#1  0x00007ffff7d0f741 in cl::sycl::detail::DispatchHostTask::operator()() const () from /foo/llvm/build/lib/libsycl.so.5


```
but that only works for the _rt variant, not the _ct ones, as everything is resolved at compile-time (so everything comes from libcblas in the ct case even with the workaround).
Am I missing something here ?

# Version
git latest, commit 28c6deecfe

# Environment
oneMKL works with multiple HW and backend libraries and also depends on the
compiler and build environment. Include
the following information to help reproduce the issue:
* Backend library version: mkl latest
* OS name and version: ubuntu 22.04 (wsl2, but we saw the behaviour on other platforms)
* Compiler version (intel/llvm open source, commit 4658b61ab0a )
* CMake output log [log_cmake.txt](https://github.com/oneapi-src/oneMKL/files/8833947/log_cmake.txt)

# Steps to reproduce
build with reference lapack as ref, clang from llcm/intel in the path, and MKLROOT set.
example for debug purposes
 cmake -DCMAKE_CXX_COMPILER=clang++ 
-DCMAKE_C_COMPILER=clang 
-DENABLE_CUBLAS_BACKEND=False 
-DENABLE_MKLCPU_BACKEND=True 
-DENABLE_MKLGPU_BACKEND=False 
-DCMAKE_CXX_FLAGS="-O0 -g3 -DCBLAS_ORDER=CBLAS_LAYOUT" 
-DBUILD_FUNCTIONAL_TESTS=ON  
-DREF_BLAS_ROOT=/path/to/lapack/build/ 
-DREF_LAPACK_ROOT=/path/to/lapack/build/ ..

make 
check behaviour with saxpy usm (on RT test):

gdb --args ./bin/test_main_blas_rt "--gtest_filter=AxpyUsmTestSuite/AxpyUsmTests.RealSinglePrecision/Column_Major_SYCL_host_device" "--gtest_also_run_disabled_tests"

break on cblas_saxpy to see backtrace of various calls.

# Observed behavior
All cblas calls in the test come from libcblas

#0  0x00007ffff7f9cdd0 in cblas_saxpy () from /foo/lapack/build/lib/libcblas.so.3
#1  0x00007ffff7d0f741 in cl::sycl::detail::DispatchHostTask::operator()() const () from /foo/llvm/build/lib/libsycl.so.5

# Expected behavior

Half (even) of the calls to cblas saxpy should come from MKL, the other half (odd) would still be from the reference libcblas library

#0  0x00007fffee720f00 in cblas_saxpy () from /opt/intel/oneapi/mkl/latest/lib/intel64/libmkl_intel_ilp64.so.2
#1  0x00007ffff7d0f741 in cl::sycl::detail::DispatchHostTask::operator()() const () from /foo/llvm/build/lib/libsycl.so.5

### PR DESCRIPTION
**Pull request by dnhsieh-intel**
# Description

When a backend respects CBLAS symbols, instead of comparing the backend against the reference libcblas library, the current testing structure would compare the reference against itself due to the conflicting symbols. This PR resolves this issue by loading reference functions at runtime into a local namespace.

Fixes #204

# Tests
Diagnostic messages were inserted in the Netlib `cblas_saxpy` and the oneMKL `axpy` unit test to check when the reference was called. More specifically:
- In [the Netlib cblas_saxpy.c](https://github.com/Reference-LAPACK/lapack/blob/master/CBLAS/src/cblas_saxpy.c)
  ``` c
  void cblas_saxpy( const CBLAS_INT N, const float alpha, const float *X,
                         const CBLAS_INT incX, float *Y, const CBLAS_INT incY)
  {
     printf("   Netlib cblas_saxpy called\n");
  #ifdef F77_INT
     F77_INT F77_N=N, F77_incX=incX, F77_incY=incY;
  #else
     #define F77_N N
     #define F77_incX incX
     #define F77_incY incY
  #endif
     F77_saxpy( &F77_N, &alpha, X, &F77_incX, Y, &F77_incY);
  }
  ```
- In [the oneMKL unit test axpy.cpp](https://github.com/oneapi-src/oneMKL/blob/develop/tests/unit_tests/blas/level1/axpy.cpp)
  ``` cpp
  template <typename fp>
  int test(device *dev, oneapi::mkl::layout layout, int N, int incx, int incy, fp alpha) {
      // Prepare data.
      vector<fp> x, y, y_ref;
  
      rand_vector(x, N, incx);
      rand_vector(y, N, incy);
      y_ref = y;
  
      // Call Reference AXPY.
      std::cout << "Call reference axpy" << std::endl;
      using fp_ref = typename ref_type_info<fp>::type;
      const int N_ref = N, incx_ref = incx, incy_ref = incy;
  
      ::axpy(&N_ref, (fp_ref *)&alpha, (fp_ref *)x.data(), &incx_ref, (fp_ref *)y_ref.data(),
             &incy_ref);
  
      // Call DPC++ AXPY.
      std::cout << "Call DPC++ axpy" << std::endl;
      ......
  ```

We use the _ct test as an example in the following. The results of the _rt test are the same.

Since the conflicts of symbols between the MKL backend and the reference have been fixed in PR #210, the reference function was called appropriately both with and without this PR:
```
$ ./bin/test_main_blas_ct --gtest_filter=AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major*CPU*
Run this program with --terse_output to change the way it prints its output.
Note: Google Test filter = AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major*CPU*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AxpyTestSuite/AxpyTests
[ RUN      ] AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major_Intel_R__Core_TM__i7_6770HQ_CPU___2_60GHz
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
[       OK ] AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major_Intel_R__Core_TM__i7_6770HQ_CPU___2_60GHz (125 ms)
[----------] 1 test from AxpyTestSuite/AxpyTests (125 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (125 ms total)
[  PASSED  ] 1 test.
```

To simulate the situation of conflicting symbols, [the commit 634d7d2](https://github.com/oneapi-src/oneMKL/tree/634d7d25c7bed523d1157cb46177c4d7494862d2) right before PR #210 was used. Based on the commit, the diagnostic messages were:
```
$ ./bin/test_main_blas_ct --gtest_filter=AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major*CPU*
Run this program with --terse_output to change the way it prints its output.
Note: Google Test filter = AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major*CPU*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AxpyTestSuite/AxpyTests
[ RUN      ] AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major_Intel_R__Core_TM__i7_6770HQ_CPU___2_60GHz
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
   Netlib cblas_saxpy called
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
   Netlib cblas_saxpy called
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
   Netlib cblas_saxpy called
[       OK ] AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major_Intel_R__Core_TM__i7_6770HQ_CPU___2_60GHz (104 ms)
[----------] 1 test from AxpyTestSuite/AxpyTests (104 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (104 ms total)
[  PASSED  ] 1 test.
```

We then applied the changes in this PR to the commit. We can see from the messages that the changes fixed the issue.
```
$ ./bin/test_main_blas_ct --gtest_filter=AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major*CPU*
Run this program with --terse_output to change the way it prints its output.
Note: Google Test filter = AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major*CPU*
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AxpyTestSuite/AxpyTests
[ RUN      ] AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major_Intel_R__Core_TM__i7_6770HQ_CPU___2_60GHz
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
Call reference axpy
   Netlib cblas_saxpy called
Call DPC++ axpy
[       OK ] AxpyTestSuite/AxpyTests.RealSinglePrecision/Column_Major_Intel_R__Core_TM__i7_6770HQ_CPU___2_60GHz (116 ms)
[----------] 1 test from AxpyTestSuite/AxpyTests (116 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (117 ms total)
[  PASSED  ] 1 test.
```

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a log: [blas_lnx_log.txt](https://github.com/oneapi-src/oneMKL/files/10036178/blas_lnx_log.txt)
- [x] Have you formatted the code using clang-format?

### CODE REVIEW

File: tests/unit_tests/blas/include/reference_blas_templates.hpp [hunk 1]
```diff
@@ -39,74 +39,2377 @@
...
+    int izamax_res = 0;
+    if (cblas_library() != NULL) {
+        if (cblas_izamax_p == NULL)
+            cblas_izamax_p = (int (*)(const int n, const void *x, const int incx))GET_FUNC(
+                h_libcblas, "cblas_izamax");
+        if (cblas_izamax_p != NULL)
+            izamax_res = cblas_izamax_p(n, x, incx);
+    }
+    return izamax_res;
+}
```
Comment (andrewtbarker) [inline tests/unit_tests/blas/include/reference_blas_templates.hpp]: This file is already huge, I suggest putting everything above this point in a separate file (maybe named `reference_blas_wrappers.hpp` or something similar) and including it in `reference_blas_templates.hpp`. I actually wish there was a way to avoid so much wrapping and indirection but probably this is the best we can do.

**Review by andrewtbarker — COMMENTED** [review]
Thanks for this pull request and the thorough investigation! I have a question about this:

> To simulate the situation of conflicting symbols, [the commit 634d7d2](https://github.com/oneapi-src/oneMKL/tree/634d7d25c7bed523d1157cb46177c4d7494862d2) right before PR https://github.com/oneapi-src/oneMKL/pull/210 was used.

Why this particular commit? The problem of using reference blas for both baseline and test persists even after #210.

File: tests/unit_tests/CMakeLists.txt [hunk 2]
```diff
@@ -152,15 +152,15 @@ foreach(domain ${TARGET_DOMAINS})
   # Find individual tests within executable
     gtest_discover_tests(test_main_${domain}_rt
       PROPERTIES BUILD_RPATH ${CMAKE_BINARY_DIR}/lib
-      PROPERTIES ENVIRONMENT LD_LIBRARY_PATH=${CMAKE_BINARY_DIR}/lib:$ENV{LD_LIBRARY_PATH}
+      PROPERTIES ENVIRONMENT LD_LIBRARY_PATH=${CMAKE_BINARY_DIR}/lib:${CBLAS_LIB_DIR}:$ENV{LD_LIBRARY_PATH}
```
Comment (mkrainiuk) [inline tests/unit_tests/CMakeLists.txt]: I don't think we need this library for any other domains except BLAS, could you please add a check that `domain` is BLAS and only in this case add the extra library?

File: tests/unit_tests/CMakeLists.txt [hunk 3]
```diff
@@ -152,15 +152,15 @@ foreach(domain ${TARGET_DOMAINS})
...
       PROPERTIES TEST_PREFIX ${DOMAIN_PREFIX}/RT/
       DISCOVERY_TIMEOUT 30
     )
   endif()
 
   gtest_discover_tests(test_main_${domain}_ct
     PROPERTIES BUILD_RPATH ${CMAKE_BINARY_DIR}/lib
-    PROPERTIES ENVIRONMENT LD_LIBRARY_PATH=${CMAKE_BINARY_DIR}/lib:$ENV{LD_LIBRARY_PATH}
+    PROPERTIES ENVIRONMENT LD_LIBRARY_PATH=${CMAKE_BINARY_DIR}/lib:${CBLAS_LIB_DIR}:$ENV{LD_LIBRARY_PATH}
```
Comment (mkrainiuk) [inline tests/unit_tests/CMakeLists.txt]: Please add `domain` check here if possible

File: tests/unit_tests/CMakeLists.txt [hunk 4]
```diff
@@ -44,7 +44,7 @@ set(blas_TEST_LIST
         blas_batch
         blas_extensions)
 
-set(blas_TEST_LINK ${CBLAS_LINK})
+set(blas_TEST_LINK "")
```
Comment (mkrainiuk) [inline tests/unit_tests/CMakeLists.txt:47]: Do we still need this line?

File: tests/unit_tests/blas/include/reference_blas_templates.hpp [hunk 5]
```diff
@@ -39,74 +39,2377 @@
...
 
 extern "C" {
-static LIB_TYPE h = NULL;
-static void (*csrot_p)(const int *N, void *X, const int *incX, void *Y, const int *incY,
+static LIB_TYPE h_libblas = NULL;
+static LIB_TYPE blas_library() {
+    if (h_libblas == NULL) {
+        h_libblas = GET_LIB_HANDLE(REF_BLAS_LIBNAME);
+        if (h_libblas == NULL) {
+            throw oneapi::mkl::library_not_found("BLAS", "blas_library()",
```
Comment (mkrainiuk) [inline tests/unit_tests/blas/include/reference_blas_templates.hpp]: Does it make sense to print REF_BLAS_LIBNAME here to provide more information about what exact library we tried to load?

**Review by mkrainiuk — COMMENTED** [review]
Thanks for the PR! I have several questions to the changes.

File: tests/unit_tests/blas/include/reference_blas_templates.hpp (hunk 1 above)
Comment (dnhsieh-intel) [reply tests/unit_tests/blas/include/reference_blas_templates.hpp]: > The problem of using reference blas for both baseline and test persists even after https://github.com/oneapi-src/oneMKL/pull/210.

That's weird. I didn't see the problem in the develop using either gdb or output messages. Could you share what you observed please?

Comment (andrewtbarker) [reply tests/unit_tests/blas/include/reference_blas_templates.hpp]: This open source product calls oneMKL CPU backend via DPC++ interfaces, which then call cblas symbols. I recall that those symbols were resolving to netlib even after #210. This is what I meant with [this comment](https://github.com/oneapi-src/oneMKL/issues/204#issuecomment-1230806775). But you have investigated this more closely than I did, I might be wrong.

Comment (dnhsieh-intel) [reply tests/unit_tests/blas/include/reference_blas_templates.hpp]: I think we might have dodged the conflict. After PR #210, it looks to me that it is the _64 APIs that are called in the mklcpu backend, e.g., `cblas_saxpy_64`.

The wrappers were moved to `reference_blas_wrappers.hpp`. (commit [f17ce6c](https://github.com/oneapi-src/oneMKL/pull/251/commits/f17ce6c48dc27c299a4a3f8dc4842e8d2d5a604b))

File: tests/unit_tests/CMakeLists.txt (hunk 2 above)
Comment (dnhsieh-intel) [reply tests/unit_tests/CMakeLists.txt]: Good point! Addressed in the commit [f762e6f](https://github.com/oneapi-src/oneMKL/pull/251/commits/f762e6f871af3eb77133374852d1b0ccf37f97ed).

File: tests/unit_tests/CMakeLists.txt (hunk 3 above)
Comment (dnhsieh-intel) [reply tests/unit_tests/CMakeLists.txt]: Addressed in the commit [f762e6f](https://github.com/oneapi-src/oneMKL/pull/251/commits/f762e6f871af3eb77133374852d1b0ccf37f97ed).

File: tests/unit_tests/CMakeLists.txt (hunk 4 above)
Comment (dnhsieh-intel) [reply tests/unit_tests/CMakeLists.txt:47]: No, we don't, but it would improve readability as we don't need to worry if `blas_TEST_LINK` is defined somewhere else. In addition, it is consistent with the `rng` domain:
https://github.com/oneapi-src/oneMKL/blob/15946f83fc25ba130f73a65bcf3174639fb8c1a0/tests/unit_tests/CMakeLists.txt#L55-L60

File: tests/unit_tests/blas/include/reference_blas_templates.hpp (hunk 5 above)
Comment (dnhsieh-intel) [reply tests/unit_tests/blas/include/reference_blas_templates.hpp]: Addressed in the commit [f17ce6c](https://github.com/oneapi-src/oneMKL/pull/251/commits/f17ce6c48dc27c299a4a3f8dc4842e8d2d5a604b).

An example of the error message:
```
C++ exception with description "oneMKL: BLAS/cblas_library(): library not found: failed to load CBLAS library /nfs/site/proj/mkl/mirror/NN/tools/netlib/3.10.0_5d4180c/blas/lnx/lib/libcblas.so" thrown in the test body.
```

**Comment by dnhsieh-intel** [comment]
Log of the commit [f17ce6c](https://github.com/oneapi-src/oneMKL/pull/251/commits/f17ce6c48dc27c299a4a3f8dc4842e8d2d5a604b): [blas_lnx_log_f17ce6c.txt](https://github.com/oneapi-src/oneMKL/files/10052739/blas_lnx_log_f17ce6c.txt)
100% tests passed, 0 tests failed out of 3530

File: tests/unit_tests/blas/include/reference_blas_templates.hpp (hunk 1 above)
Comment (andrewtbarker) [reply tests/unit_tests/blas/include/reference_blas_templates.hpp]: Oh, that makes sense, the _64 wrappers were a separate change. Thanks!

**Review by andrewtbarker — APPROVED** [review]

File: tests/unit_tests/CMakeLists.txt (hunk 3 above)
Comment (mkrainiuk) [reply tests/unit_tests/CMakeLists.txt]: Thank you! I have one more question regarding Windows build, we define LD_LIBRARY_PATH here for Netlib libraires but we don't define PATH on Windows, does it make sense to update PATH instead of LD_LIBRARY_PATH in case of Windows?

**Review by mkrainiuk — APPROVED** [review]
The changes look good to me. Thank you!

File: tests/unit_tests/CMakeLists.txt (hunk 3 above)
Comment (dnhsieh-intel) [reply tests/unit_tests/CMakeLists.txt]: I thought this is straightforward. I was wrong...

On Windows, if we try to set PATH, which is a semicolon-separated list, in `gtest_discover_tests`, for example:
``` cmake
gtest_discover_tests(test_main_${domain}_ct PROPERTIES ENVIRONMENT "PATH=C:\path1;C:\path2;C:\path3")
```
After CMake's internal processing, it turns out that the actual setting will only be `PATH=C:\path1`. This seems to be [a known CMake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/21453).

Do you think we should open an issue to investigate a workaround? Right now, because users have to include Netlib in PATH to build on Windows, it's fine if they run tests directly after building. But they would encounter the "failed to load CBLAS library" error if they run tests in a separate session.

Comment (mkrainiuk) [reply tests/unit_tests/CMakeLists.txt]: I think it's worth adding a note to our README about Netlib required in PATH on Windows. And we also can investigate potential W/A as separated issue. I don't think we need to mix the current issue and the Windows one in this PR.

Comment (dnhsieh-intel) [reply tests/unit_tests/CMakeLists.txt]: Will be tracked in issue #252.
