### PR TITLE
[cublas] set CUBLAS_POINTER_MODE_HOST after setting it to device

### LINKED ISSUE #92: CUDA_ERROR_ILLEGAL_ADDRESS when using level1 and higher level rutines in the same queue
# Summary

When submitting level 1 and higher-level kernels in the same queue, for the cublas backend ` CUDA_ERROR_ILLEGAL_ADDRESS` runtime error is thrown. 

I believe this is due to the fact that for some of the level1 functions the pointer mode is set to `CUBLAS_POINTER_MODE_DEVICE` but it is never set back to the default value, `CUBLAS_POINTER_MODE_HOST`, therefore the device setting remains active for all subsequent calls with that cublas handle, which seems to cause problems. Adding the line `cublasSetPointerMode(handle, CUBLAS_POINTER_MODE_HOST);` to the respective functions resolves the issue. 

The tests create a queue for every BLAS function, therefore this issue hasn't surfaced there, but it can be triggered with a simple test program.

# Version
The current oneMKL develop head is used eg: 1ed12c7

# Environment

* HW you use
 Intel Gold 6130 CPU with Nvidia gtx1080 GPUs
 * Backend library version
 Cuda 10.0
 MKL, and TBB obtained via intel installer version 2021.2.0
 * OS name and version
 Ubuntu 20.04 (fakeroot singularity container)
 * Compiler version
dpc++ compiler cloned from develop with hash: 4e26734cb87c451e0562559d5d6f83b7eabcaea3
compiled with:
`buildbot/configure.py --cuda`
`and buildbot/compile.py`
* CMake
[cmake.md](https://github.com/oneapi-src/oneMKL/files/6489454/cmake.md)

# Steps to reproduce
Use the following simple test program:
```
#include "oneapi/mkl.hpp"
#include <iostream>
#include <CL/sycl.hpp>

int main(){
  std::vector<double> M = {1, 1, 1, 1};
  std::vector<double> y = {3, 4};
  std::vector<double> x = {1, 1};
  
  std::vector<double> x1 = {1,1};
  std::vector<double> x2 = {2,2};

  double result = -1;

  cl::sycl::buffer<double, 1> M_buffer = cl::sycl::buffer(M.data(), cl::sycl::range<1>(M.size()));
  cl::sycl::buffer<double, 1> y_buffer = cl::sycl::buffer(y.data(), cl::sycl::range<1>(y.size()));
  cl::sycl::buffer<double, 1> x_buffer = cl::sycl::buffer(x.data(), cl::sycl::range<1>(x.size())); 

  cl::sycl::buffer<double, 1> x1_buffer = cl::sycl::buffer(x1.data(), cl::sycl::range<1>(x1.size())); 
  cl::sycl::buffer<double, 1> x2_buffer = cl::sycl::buffer(x1.data(), cl::sycl::range<1>(x1.size())); 
  
  cl::sycl::buffer<double, 1> result_buffer = cl::sycl::buffer(&result, cl::sycl::range<1>(1)); 

 auto gpu_dev = sycl::device(sycl::gpu_selector());
 sycl::queue gpu_queue(gpu_dev);
 
 oneapi::mkl::backend_selector<oneapi::mkl::backend::cublas> gpu_selector(gpu_queue);
  
 oneapi::mkl::blas::column_major::dot(gpu_selector, 2, x1_buffer, 1, x2_buffer, 1, result_buffer);
 oneapi::mkl::blas::column_major::gemv(gpu_selector, oneapi::mkl::transpose::nontrans, 2, 2,
                                   1.0, M_buffer, 2, x_buffer, 1, 1.0, y_buffer, 1.0);
}
```
compile:
`LD_LIBRARY_PATH=/home/sbalint/hipSYCL-main/dpc++-hand/llvm/build/install/lib/:/opt/hipSYCL/cuda/lib64:$LD_LIBRARY_PATH /home/sbalint/hipSYCL-main/dpc++-hand/llvm/build/install/bin/clang++ -fsycl  -fsycl-targets=nvptx64-nvidia-cuda-sycldevice  -I /home/sbalint/hipSYCL-main/oneMKL-install/include/ -L/home/sbalint/hipSYCL-main/oneMKL-install/lib/ -lonemkl_blas_cublas test.cpp `
and run:
`LD_LIBRARY_PATH=/home/sbalint/hipSYCL-main/dpc++-hand/llvm/build/install/lib/:/opt/hipSYCL/cuda/lib64:/home/sbalint/hipSYCL-main/oneMKL-install/lib/:$LD_LIBRARY_PATH ./a.out `

# Observed behavior
The following runtime error is displayed:
```
Singularity> LD_LIBRARY_PATH=/home/sbalint/hipSYCL-main/dpc++-hand/llvm/build/install/lib/:/opt/hipSYCL/cuda/lib64:/home/sbalint/hipSYCL-main/oneMKL-install/lib/:$LD_LIBRARY_PATH ./a.out 
Hello

PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        cuda_piEnqueueMemBufferRead
        Source Location: /root/hipSYCL-main/dpc++-hand/llvm/sycl/plugins/cuda/pi_cuda.cpp:2199


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        wait
        Source Location: /root/hipSYCL-main/dpc++-hand/llvm/sycl/plugins/cuda/pi_cuda.cpp:447


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        wait
        Source Location: /root/hipSYCL-main/dpc++-hand/llvm/sycl/plugins/cuda/pi_cuda.cpp:447


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        wait
        Source Location: /root/hipSYCL-main/dpc++-hand/llvm/sycl/plugins/cuda/pi_cuda.cpp:447


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        enqueueEventWait
        Source Location: /root/hipSYCL-main/dpc++-hand/llvm/sycl/plugins/cuda/pi_cuda.cpp:473


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        _pi_event
        Source Location: /root/hipSYCL-main/dpc++-hand/llvm/sycl/plugins/cuda/pi_cuda.cpp:331


PI CUDA ERROR:
        Value:           700
        Name:            CUDA_ERROR_ILLEGAL_ADDRESS
        Description:     an illegal memory access was encountered
        Function:        wait
        Source Location: /root/hipSYCL-main/dpc++-hand/llvm/sycl/plugins/cuda/pi_cuda.cpp:447
```

# Expected behavior
The program executes without errors

### PR DESCRIPTION
**Pull request by sbalint98**
This PR is a solution proposal for issue #92 

# Description

I believe this is the most simplistic way to solve the issue described in #92. 

Fixes #92 

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a log.
* on CPU device: 
[cpu_tests.log](https://github.com/oneapi-src/oneMKL/files/6489583/cpu_tests.log)
* on GPU: see issue #93 
- [x] Have you formatted the code using clang-format?
- [ ] Have you added relevant regression tests?
- [x] Have you included information on how to reproduce the issue (either in a
      GitHub issue or in this PR)?
see #92

### CODE REVIEW

**Comment by vrpascuzzi** [comment]
Hi, @sbalint98.

> on GPU: see issue #93

Can you attach the unit test for GPU, showing all tests now run and pass successfully with your patch applied? The linked log above only shows the current failing test output.

**Comment by sbalint98** [comment]
Hi @vrpascuzzi, thank you for your reply.

On GPU, unfortunately, I am not able to run the tests, because of the issue described in #93. The problem is that the GPU memory gets depleted, and the tests start to fail with `CUDA_ERROR_OUT_OF_MEMORY`, this also occurs for the current develop branch and seems to be independent of the issue of `CUDA_ERROR_ILLEGAL_ADDRESS` getting thrown when level 1 and higher-level routines are mixed ( issue #93 ) that this PR intends to fix. 

Should I make this PR a draft unless #93 is resolved and I am able to run the unit tests on GPU as well?

EDIT: I ticked out the all unit-tests pass locally button.

**Comment by mmeterel** [comment]
@sbalint98 Thanks for the PR. I have tested it locally and verified that all GPU tests pass as well. 

(In my local runs, I don't see the issue reported in #93. I will take a look at #93 separately.)

File: src/blas/backends/cublas/cublas_level1.cpp [hunk 1]
```diff
@@ -56,6 +56,7 @@ inline void asum(Func func, cl::sycl::queue &queue, int64_t n, cl::sycl::buffer<
             cublasStatus_t err;
             // ASUM does not support negative index
             CUBLAS_ERROR_FUNC(func, err, handle, n, x_, std::abs(incx), res_);
+            cublasSetPointerMode(handle, CUBLAS_POINTER_MODE_HOST);
```
Comment (mmeterel) [inline src/blas/backends/cublas/cublas_level1.cpp:62]: Could you please add a brief description on the purpose of this change? (similar comment for the other ones as well)

**Review by mmeterel — COMMENTED** [review]
- Could you please add the same edits for ROT API as well?
- Could you please format the edited file using clang-format?

**Comment by mmeterel** [comment]
Attaching the log of the local runs for GPU.

[cublas_gpu_test.log](https://github.com/oneapi-src/oneMKL/files/6510861/cublas_gpu_test.log)

**Comment by sbalint98** [comment]
Thank you for the review, added the edits for ROT and the description to all the changes. I also applied the clang-format with the configuration provided, but the file was already well-formatted.

File: src/blas/backends/cublas/cublas_level1.cpp [hunk 2]
```diff
@@ -306,12 +322,16 @@ inline void rot(Func func, cl::sycl::queue &queue, int64_t n, cl::sycl::buffer<T
             // CUBLAS_POINTER_MODE_DEVICE mode otherwise it causes the segmentation
             // fault. When it is set to device it is users responsibility to
             // synchronise as the function is completely asynchronous.
-            // cublasSetPointerMode(handle, CUBLAS_POINTER_MODE_DEVICE);
+            cublasSetPointerMode(handle, CUBLAS_POINTER_MODE_DEVICE);
```
Comment (mmeterel) [inline src/blas/backends/cublas/cublas_level1.cpp]: @sbalint98 Sorry for misleading you on the ROT function. Switching to CUBLAS_POINTER_MODE_DEVICE actually causes CUDA_ERROR_ILLEGAL_ADDRESS since there is no scalar result returned by ROT on the device.  

Could you please revert the changes for ROT and also remove the commented out section regarding CUBLAS_POINTER_MODE_DEVICE?

Comment (sbalint98) [reply src/blas/backends/cublas/cublas_level1.cpp]: Thanks for noticing this, I should have cought it as well.

**Review by mmeterel — APPROVED** [review]

File: src/blas/backends/cublas/cublas_level1.cpp (hunk 2 above)
Comment (mmeterel) [reply src/blas/backends/cublas/cublas_level1.cpp]: Thanks for the updates.

**Review by mkrainiuk — APPROVED** [review]
Looks good to me, thank you!

**Review by vmalia — APPROVED** [review]
