### PR TITLE
Changed pi_context to ur_context_handle_t and include pi.hpp to ur.hpp

### LINKED ISSUE #558: Build with open-source DPC++-LLVM (`clang++`) broken due to compiler removal of `sycl/detail/pi.hpp`
## Summary
The [open-source Intel LLVM compiler](https://github.com/intel/llvm) recently removed the header file `sycl/detail/pi.hpp` (among others) in their [PR#14145](https://github.com/intel/llvm/pull/14145/). As a result, building oneMKL Interfaces with latest nightly builds of the compiler is broken. Issue is reproducible with [latest nightly drops at this link](https://github.com/intel/llvm/releases), but  not reproducible (builds fine) with some slightly older drops, e.g. `nightly-07-22`.

## Details
* Compiler version:
  ```
  clang version 19.0.0git (https://github.com/intel/llvm.git 44c34c14326a189f719fbbe3393a8ee4a790f1c2)
  ```
* CMake output log:
  ```
  -- CMAKE_BUILD_TYPE: Release
  -- TARGET_DOMAINS: blas
  -- Looking for dpc++
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /export/users/gchoudha/oneMKL-interfaces/build
  Consolidate compiler generated dependencies of target onemkl_blas
  [ 10%] Built target onemkl_blas
  Consolidate compiler generated dependencies of target onemkl_blas_cublas_obj
  [ 20%] Building CXX object bin/blas/backends/cublas/CMakeFiles/onemkl_blas_cublas_obj.dir/cublas_level1.cpp.o
  In file included from /export/users/gchoudha/oneMKL-interfaces/src/blas/backends/cublas/cublas_level1.cpp:20:
  In file included from /export/users/gchoudha/oneMKL-interfaces/src/blas/backends/cublas/cublas_task.hpp:34:
  /export/users/gchoudha/oneMKL-interfaces/src/blas/backends/cublas/cublas_scope_handle.hpp:31:10: fatal error: 'sycl/detail/pi.hpp' file not found
     31 | #include <sycl/detail/pi.hpp>
        |          ^~~~~~~~~~~~~~~~~~~~
  1 error generated.
  ```

### PR DESCRIPTION
**Pull request by keyradical**
# Description
After [plugin interface removal patch](https://github.com/intel/llvm/pull/14145) in **intel/llvm**, the oneMKL build broke. This PR fixes it by:
- changing all occurences of `#include pi.hpp` to `ur.hpp`
- changing `pi_context` to `ur_context_handle_t`

Also, for the build to work correctly again, this patch is needed:
- https://github.com/intel/llvm/pull/14830

### CODE REVIEW

**Comment by hjabird** [comment]
Hi Konrad,
A few questions:
* Can you provide test logs for everything you've changed
  * cublas, rocblas, cusolver, rocsolver
* I'm confused about the compiler compatibility right now?

**Comment by keyradical** [comment]
Hi Hugh,

Yes, we've realized this would break compatibility with previous DPC++ releases so I'm working on adding some ifdefs. I'll provide the test logs as well.

**Comment by keyradical** [comment]
Sorry for a delay with this as I was sick.

Here are the logs when using 2024.2.1 DPC++:
[amd_test_main_lapack_rt.txt](https://github.com/user-attachments/files/16612127/amd_test_main_lapack_rt.txt)
[amd_test_main_lapack_ct.txt](https://github.com/user-attachments/files/16612128/amd_test_main_lapack_ct.txt)
[amd_test_main_blas_rt.txt](https://github.com/user-attachments/files/16612132/amd_test_main_blas_rt.txt)
[amd_test_main_blas_ct.txt](https://github.com/user-attachments/files/16612135/amd_test_main_blas_ct.txt)
[amd_example_lapack_getrs_usm.txt](https://github.com/user-attachments/files/16612137/amd_example_lapack_getrs_usm.txt)
[amd_example_blas_gemm_usm.txt](https://github.com/user-attachments/files/16612138/amd_example_blas_gemm_usm.txt)

[nvidia_test_main_lapack_rt.txt](https://github.com/user-attachments/files/16612147/nvidia_test_main_lapack_rt.txt)
[nvidia_test_main_lapack_ct.txt](https://github.com/user-attachments/files/16612149/nvidia_test_main_lapack_ct.txt)
[nvidia_test_main_blas_rt.txt](https://github.com/user-attachments/files/16612151/nvidia_test_main_blas_rt.txt)
[nvidia_test_main_blas_ct.txt](https://github.com/user-attachments/files/16612154/nvidia_test_main_blas_ct.txt)
[nvidia_example_lapack_getrs_usm.txt](https://github.com/user-attachments/files/16612156/nvidia_example_lapack_getrs_usm.txt)
[nvidia_example_blas_gemm_usm.txt](https://github.com/user-attachments/files/16612159/nvidia_example_blas_gemm_usm.txt)

For 2025 DPC++ testing there are some failures with both Nvidia and AMD but I think they are unrelated to this patch. Likely the problem is with the compiler but I'm still investigating those.

**Comment by gajanan-choudhary** [comment]
Looks like this is the fix for #558 that I just opened.

File: src/blas/backends/cublas/cublas_scope_handle.hpp [hunk 1]
```diff
@@ -28,12 +28,23 @@
...
 #else
 #include <CL/sycl/backend/cuda.hpp>
 #include <CL/sycl/context.hpp>
+#endif
+
+// After Plugin Interface removal in DPC++ ur.hpp is the new include
+#if __has_include(<sycl/detail/ur.hpp>)
+#include <sycl/detail/ur.hpp>
+#ifndef _PI_INTERFACE_REMOVED_
+#define _PI_INTERFACE_REMOVED_
```
Comment (Rbiessy) [inline src/blas/backends/cublas/cublas_scope_handle.hpp]: Is this define only used as a shorthand inside oneMKL?
If so we should start naming these defines like `ONEAPI_ONEMKL_PI_INTERFACE_REMOVED` to clarify that it is specific to this project.

Comment (keyradical) [reply src/blas/backends/cublas/cublas_scope_handle.hpp]: Yes, this is only in oneMKL. Changed it to `ONEAPI_ONEMKL_PI_INTERFACE_REMOVED`.

**Review by Rbiessy — APPROVED** [review]

**Comment by Rbiessy** [comment]
@oneapi-src/onemkl-admin this change is needed to get the CI working with a nightly compiler, a second approval would be useful.

**Review by andrewtbarker — APPROVED** [review]
This all looks fine to me. Should we have someone from @oneapi-src/onemkl-lapack-write take a quick look at the solvers changes?

**Comment by Rbiessy** [comment]
Ideally yes but I am planning to merge this tomorrow morning unless I hear an objection.

File: src/blas/backends/cublas/cublas_scope_handle.hpp [hunk 2]
```diff
@@ -28,12 +28,23 @@
...
 #include <sycl/context.hpp>
-#include <sycl/detail/pi.hpp>
 #else
 #include <CL/sycl/backend/cuda.hpp>
 #include <CL/sycl/context.hpp>
+#endif
+
+// After Plugin Interface removal in DPC++ ur.hpp is the new include
+#if __has_include(<sycl/detail/ur.hpp>)
+#include <sycl/detail/ur.hpp>
```
Comment (AlexeySachkov) [inline src/blas/backends/cublas/cublas_scope_handle.hpp:38]: Please note that instead of removing a footgun you have just reloaded it so it will fire at you once again in upcoming months (or years) when we drop UR in favor of something else.

You should *not* use implementation details like this in your project. Why aren't use using the official SYCL interop interface, i.e. `backend_return_t<your_backend, context>`?

I'm also surprised that you are changing the type of that variable without changing any of its uses, meaning that the type doesn't matter for you because it will be erased at some point. Wouldn't it be better to use some opaque type right away to avoid dependency on particular SYCL implementation?
