### PR TITLE
[DFT] remove compile-time compute dispatch from dft domain

### LINKED ISSUE #309: [DFT] Building multiple DFT backends at once causes linking conflicts
# Summary
When building multiple DFT backends at once, each backend defines a symbol for the many `oneapi::mkl::dft::compute_forward(...)` and `oneapi::mkl::dft::compute_backward(...)` compilation time dispatch overloads, so at linking time either one can be chosen.
To get around this I tried linking just one of the two backends, but then compilation failed because of an undefined reference to `oneapi::mkl::dft::detail::descriptor<...>::commit(oneapi::mkl::backend_selector<other_backend>)`. This is because both `ENABLE_MKLCPU_BACKEND`  and `ENABLE_MKLGPU_BACKEND` are defined in the preprocessor so both commits are defined here - 
https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/dft/detail/descriptor_impl.hpp#L63 .
I tried getting around this by providing a definition of `commit` but made it a weak symbol so it can be overridden when the appropriate backend is linked. This led to problems when running the tests because https://github.com/oneapi-src/oneMKL/blob/develop/tests/unit_tests/main_test.cpp#L113 is still picking up both devices.

I believe other interfaces get around this by having a `backend_selector<backend::BACKEND>` parameter on all the functions, like here https://github.com/oneapi-src/oneMKL/blob/develop/include/oneapi/mkl/blas/detail/blas_ct_backends.hxx. I think the best course of action might be a spec change to include a `backend_selector` on `compute_forward` and `compute_backward`.

# Version
This on develop, I specifically tested githash 005c3c79a44974fc8c3adebfa71d94b0fe005f33

# Steps to reproduce
Build with both ENABLE_MKLCPU_BACKEND and ENABLE_MKLGPU_BACKEND set to 1.

# Observed behavior
When running `test_main_dft_ct` I get this output:
```
finlay@devpc-c310:~/perf/oneMKL/build$ ./bin/test_main_dft_ct 
Run this program with --terse_output to change the way it prints its output.
[==========] Running 488 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 240 tests from ComputeTestSuite/ComputeTests_in_place
[ RUN      ] ComputeTestSuite/ComputeTests_in_place.COMPLEX_SINGLE_in_place_buffer/sizes_8_batches_1_Intel_R__UHD_Graphics_750__0x4c8a_
Skipping test because: "oneMKL: DFT/compute_forward: function is not implemented Not implemented for MKLCPU"
...
```
# Expected behavior
The MKLGPU `compute_forward` should be called.

### PR DESCRIPTION
**Pull request by FMarno**
# Description

The current design of compile-time dispatch for the DFT domain causes multiple definitions for the `compute_forward/backward` functions, leading to linking the wrong symbols and undesirable behaviour. This PR removes the compile-time dispatch functions so this is no longer an issue.

This PR also attempts to simplify the library in a couple of ways:
* removing many of the internal implementations of `compute_forward/backward`, moving the complexity to a templated header which will cast the types.
* removing `compute_forward/backward` from the function table. These are called via a virtual function on `commit_impl` now.

Fixes #309

# Checklist

## All Submissions

- [x] Do all unit tests pass locally? Attach a log.
- [x] Have you formatted the code using clang-format?

## Bug fixes

- [x] Have you added relevant regression tests? - N/A
- [x] Have you included information on how to reproduce the issue (either in a
      GitHub issue or in this PR)?

### CODE REVIEW

**Comment by FMarno** [comment]
test logs:
[mklcpu_mklgpu_run.txt](https://github.com/oneapi-src/oneMKL/files/11948487/mklcpu_mklgpu_run.txt)
[cufft_run.log](https://github.com/oneapi-src/oneMKL/files/11948495/cufft_run.log)
[rocfft_run.log](https://github.com/oneapi-src/oneMKL/files/11948496/rocfft_run.log)

**Review by Rbiessy — APPROVED** [review]
That looks fine to me. I just want to clarify in this PR that this does not change the interface so the `compile_time_dispatching` examples still run like before but the backends are not truly dispatched at compile time, just like the RNG domain.

**Comment by FMarno** [comment]
> That looks fine to me. I just want to clarify in this PR that this does not change the interface so the `compile_time_dispatching` examples still run like before but the backends are not truly dispatched at compile time, just like the RNG domain.

That's correct. Only the commit is compile-time in the compile-time tests.

File: include/oneapi/mkl/dft/backward.hpp [hunk 1]
```diff
@@ -26,51 +26,105 @@
...
+
 namespace oneapi::mkl::dft {
 //Buffer version
 
 //In-place transform
 template <typename descriptor_type, typename data_type>
-void compute_backward(descriptor_type &desc, sycl::buffer<data_type, 1> &inout);
+void compute_backward(descriptor_type &desc, sycl::buffer<data_type, 1> &inout) {
+    using fwd_type = typename detail::descriptor_info<descriptor_type>::forward_type;
+    auto type_corrected_inout = inout.template reinterpret<fwd_type, 1>(
```
Comment (hjabird) [inline include/oneapi/mkl/dft/backward.hpp:41]: In quite a few places, buffers are reinterpreted to a "correct" type without checking the validity of the input types. I think more type checking is needed here. Eg.
* A user might be lead to expect that eg. passing single-precision data to a double precision transform is a supported operation.
* A user might want errors on passing in eg. integers.

File: include/oneapi/mkl/dft/detail/commit_impl.hpp [hunk 2]
```diff
@@ -26,42 +26,88 @@
...
 
     // rule of three
-    commit_impl(const commit_impl& other) = delete;
-    commit_impl& operator=(const commit_impl& other) = delete;
+    commit_impl(const commit_impl &other) = delete;
+    commit_impl &operator=(const commit_impl &other) = delete;
     virtual ~commit_impl() = default;
 
-    sycl::queue& get_queue() noexcept {
+    sycl::queue &get_queue() noexcept {
```
Comment (hjabird) [inline include/oneapi/mkl/dft/detail/commit_impl.hpp:58]: There are formatting changes - was the original incorrectly formatted?

**Comment by lhuot** [comment]
@anantsrivastava30 could you please take a look at this PR? Thanks!

File: include/oneapi/mkl/dft/detail/dft_ct.hxx [hunk 3]
```diff
@@ -25,96 +25,114 @@ ONEMKL_EXPORT dft::detail::commit_impl<prec, dom> *create_commit(
...
+using scalar = typename detail::descriptor_info<descriptor_type>::scalar_type;
+template <typename descriptor_type>
+using fwd = typename detail::descriptor_info<descriptor_type>::forward_type;
+template <typename descriptor_type>
+using bwd = typename detail::descriptor_info<descriptor_type>::backward_type;
+
 //In-place transform
-template <typename descriptor_type, typename data_type>
-ONEMKL_EXPORT void compute_forward(descriptor_type &desc, sycl::buffer<data_type, 1> &inout);
+template <typename descriptor_type>
```
Comment (hjabird) [inline include/oneapi/mkl/dft/detail/dft_ct.hxx:36]: Are all the function declarations in this file still needed - aren't they replaced by the virtual methods in the commit impl?

File: include/oneapi/mkl/dft/detail/types_impl.hpp [hunk 4]
```diff
@@ -39,6 +39,60 @@ struct precision_t {
...
+
+template <precision prec, domain dom>
+class descriptor;
+
+template <class... T>
+constexpr bool always_false = false;
+
+template <typename descriptor_type>
+struct descriptor_info {
+    static_assert(always_false<descriptor_type>, "Not a valid descriptor type");
```
Comment (hjabird) [inline include/oneapi/mkl/dft/detail/types_impl.hpp:62]: Yes, but won't there be an error anyway when `scalar_type`, `forward_type` and `backward_type` aren't defined? I think we should this and the `always_false` since `descriptor_info` will only ever be oneMKL developer-facing.

File: include/oneapi/mkl/dft/detail/types_impl.hpp [hunk 5]
```diff
@@ -39,6 +39,60 @@ struct precision_t {
...
+template <>
+struct descriptor_info<descriptor<precision::DOUBLE, domain::COMPLEX>> {
+    using scalar_type = double;
+    using forward_type = std::complex<double>;
+    using backward_type = std::complex<double>;
+};
+
+// compute the range of a reinterpreted buffer
+template <typename In, typename Out>
+std::size_t reinterpret_range(std::size_t size) {
```
Comment (hjabird) [inline include/oneapi/mkl/dft/detail/types_impl.hpp:102]: Throw on invalid size argument?
 
Eg `In` is `float`, `Out` is `complex<float>`, `size` is odd.

File: include/oneapi/mkl/dft/detail/commit_impl.hpp [hunk 6]
```diff
@@ -26,42 +26,88 @@
...
-    virtual void* get_handle() noexcept = 0;
+    virtual void *get_handle() noexcept = 0;
 
-    virtual void commit(const dft_values<prec, dom>&) = 0;
+    virtual void commit(const dft_values<prec, dom> &) = 0;
 
-private:
-    sycl::queue queue_;
-    mkl::backend backend_;
+    virtual void forward_ip_cc(descriptor_type &desc, sycl::buffer<fwd_type, 1> &inout) = 0;
```
Comment (hjabird) [inline include/oneapi/mkl/dft/detail/commit_impl.hpp:70]: I don't see where these new functions are overrided for the derived commit impls. What am I missing?

File: include/oneapi/mkl/dft/detail/commit_impl.hpp (hunk 2 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/detail/commit_impl.hpp:58]: I think so. I've run clang-format-10 and `clang-format-11` over it and that how it wanted to be.

File: include/oneapi/mkl/dft/detail/dft_ct.hxx (hunk 3 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/detail/dft_ct.hxx:36]: These are the ones in the `oneapi::mkl::dft::BACKEND` namespace and the virtual methods all just call the corresponding method (in `src/dft/backends/backend_compute_signature.cxx`), so yes I could just move the implementation to the `commit_impl` classes.
Maintaining the backend specific free functions does have the benefit of easily adding the compile-time dispatch in the future, but maybe things would be simpler without it. (and YAGNI principle, but the work is already done, and this is a smaller change(maybe)).
At the very least I can look at removing the `compute_forward/compute_backward` declarations from this file, since I don't think that needs to be user facing any more.

File: include/oneapi/mkl/dft/detail/types_impl.hpp (hunk 4 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/detail/types_impl.hpp:62]: There will be, but this is a good error in my opinion. e.g. I updated on of the tests to use `descriptor_t&` as the first template argument and part of the output was 
```
finlay@devpc-c310:~/perf/oneMKL/build$ ninja | head
[1/4] Building CXX object tests/unit_tests/dft/source/CMakeFiles/dft_source_rt.dir/compute_tests.cpp.o
FAILED: tests/unit_tests/dft/source/CMakeFiles/dft_source_rt.dir/compute_tests.cpp.o 
/home/finlay/intel/oneapi/compiler/2023.1.0/linux/bin/icpx  -I/home/finlay/perf/oneMKL/tests/unit_tests/dft/source/../include -I/home/finlay/perf/oneMKL/tests/unit_tests/dft/source/../../include -I/home/finlay/perf/oneMKL/include -I/home/finlay/perf/oneMKL/deps/googletest/include -I/home/finlay/perf/oneMKL/build/bin -O3 -DNDEBUG -std=gnu++17 -DCALL_RT_API -DNOMINMAX -fsycl -Wall -Wextra -Wshadow -Wconversion -Wpedantic -MD -MT tests/unit_tests/dft/source/CMakeFiles/dft_source_rt.dir/compute_tests.cpp.o -MF tests/unit_tests/dft/source/CMakeFiles/dft_source_rt.dir/compute_tests.cpp.o.d -o tests/unit_tests/dft/source/CMakeFiles/dft_source_rt.dir/compute_tests.cpp.o -c /home/finlay/perf/oneMKL/tests/unit_tests/dft/source/compute_tests.cpp
In file included from /home/finlay/perf/oneMKL/tests/unit_tests/dft/source/compute_tests.cpp:29:
In file included from /home/finlay/perf/oneMKL/tests/unit_tests/dft/source/../../include/test_helper.hpp:33:
In file included from /home/finlay/perf/oneMKL/include/oneapi/mkl.hpp:26:
In file included from /home/finlay/perf/oneMKL/include/oneapi/mkl/dft.hpp:33:
In file included from /home/finlay/perf/oneMKL/include/oneapi/mkl/dft/detail/dft_loader.hpp:30:
/home/finlay/perf/oneMKL/include/oneapi/mkl/dft/detail/types_impl.hpp:55:5: error: static assertion failed due to requirement 'always_false<oneapi::mkl::dft::detail::descriptor<oneapi::mkl::dft::detail::precision::SINGLE, oneapi::mkl::dft::detail::domain::COMPLEX> &>': Not a valid descriptor type
    static_assert(always_false<descriptor_type>, "Not a valid descriptor type");
```
potentially I could replace this with a static assert at the user-facing call site though.

File: include/oneapi/mkl/dft/detail/commit_impl.hpp (hunk 6 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/detail/commit_impl.hpp:70]: src/dft/backends/backend_compute_signature.cxx

File: include/oneapi/mkl/dft/backward.hpp (hunk 1 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/backward.hpp:41]: added in https://github.com/oneapi-src/oneMKL/pull/342/commits/a8a004c57696f512cc9f9e54aab3aaea0bedd536

File: include/oneapi/mkl/dft/detail/types_impl.hpp (hunk 4 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/detail/types_impl.hpp:62]: I'd like to keep this. When the user specifies the wrong template argument for the descriptor, it will give them a more plain error.

File: include/oneapi/mkl/dft/detail/types_impl.hpp (hunk 5 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/detail/types_impl.hpp:102]: added in https://github.com/oneapi-src/oneMKL/pull/342/commits/a8a004c57696f512cc9f9e54aab3aaea0bedd536

**Review by hjabird — APPROVED** [review]

**Review by Rbiessy — APPROVED** [review]

File: include/oneapi/mkl/dft/backward.hpp [hunk 7]
```diff
@@ -26,51 +26,137 @@
...
-                      sycl::buffer<output_type, 1> &out);
+                      sycl::buffer<output_type, 1> &out) {
+    static_assert(detail::valid_compute_arg<descriptor_type, input_type>::value,
+                  "unexpected type for input_type");
+    static_assert(detail::valid_compute_arg<descriptor_type, output_type>::value,
+                  "unexpected type for output_type");
+
+    using fwd_type = typename detail::descriptor_info<descriptor_type>::forward_type;
+    using bwd_type = typename detail::descriptor_info<descriptor_type>::backward_type;
+    auto type_corrected_in = in.template reinterpret<bwd_type, 1>(
```
Comment (anantsrivastava30) [inline include/oneapi/mkl/dft/backward.hpp:72]: whats the benifit of converting the `input_type` to 'scalar_type' which is strictly only a 'float' or 'double'.Is it because you want to supprot not only scalar and complex in/out_type but sycl::float2/4 double2/4, or some nuance of the rocFFT/cuFFT ?

**Review by anantsrivastava30 — APPROVED** [review]
I approve of this change, pending a answers to one question I had. Otherwise looks like a good solution to me. Thanks for fixing this.

File: include/oneapi/mkl/dft/backward.hpp (hunk 7 above)
Comment (FMarno) [reply include/oneapi/mkl/dft/backward.hpp:72]: I'm not completely sure I understand your question but I'll give you some info that might clarify things.
The user facing functions `compute_forward/compute_backward` currently have no restrictions on the types of `input_type` and `output_type` (though I have cheekily added some sensible ones in a static assert!). Where the functions are not user facing, I've made the parameter types purely dependent on the descriptor type, with (hopefully) sensible types chosen in the [`descriptor_info`](https://github.com/oneapi-src/oneMKL/blob/4905064a608aa89e47e152e0d0480239b5f06251/include/oneapi/mkl/dft/detail/types_impl.hpp#L61) struct.
The casts that happen in `include/oneapi/mkl/dft/backward.hpp` and `include/oneapi/mkl/dft/forward.hpp` are there to reinterpret the type that the user has chosen to the internal types.

**Comment by FMarno** [comment]
Here is an up-to-date test log.
[mklcpu_mklgpu_run.log](https://github.com/oneapi-src/oneMKL/files/12145026/mklcpu_mklgpu_run.log)
@anantsrivastava30 I will wait for you to resolve your comment before I merge

File: include/oneapi/mkl/dft/backward.hpp (hunk 7 above)
Comment (anantsrivastava30) [reply include/oneapi/mkl/dft/backward.hpp:72]: Well what I mean is this reinterpret_type converts any valid type that passes the assertions just above to its fundamental type, i.e float or double, so my question is do we really need that ? Because in the sycl API we support float/double/complex<float/double> input, and in the C_API also we accept any of the former. So what exactly are we getting out of this reinterpretation?

Comment (FMarno) [reply include/oneapi/mkl/dft/backward.hpp:72]: The type is not just reinterpreted to the scalar type, it is sometimes the `forward_type` or `backward_type` from `descriptor_info`.

I think it has a few benefits.
1. greater clarity about the expected data layout
2. reduced number of functions we need to expose from the library
3. reduced argument ambiguity (REAL_REAL in-place and COMPLEX_COMPLEX out-of-place have the same number of arguments, which can be confusing. With this system they at least take different arguments.)

Most importantly, the functions in `backward.hpp` call virtual functions on `commit_impl`, so those can't have a templated argument, so we either reinterpret or have ~100 virtual functions on the `commit_impl` class.

**Comment by anantsrivastava30** [comment]
@FMarno I have resolved my comment, please feel free to merge this.

**Comment by FMarno** [comment]
new test run after rebase [mklcpu_mklgpu_run.log](https://github.com/oneapi-src/oneMKL/files/12182384/mklcpu_mklgpu_run.log)
