### PR TITLE
Fix include when including deprecated mkl.hpp

### LINKED ISSUE #623: Cannot find "namespace_alias.hpp" when including <oneapi/mkl.hpp>
# Summary
Cannot find "namespace_alias.hpp" when including <oneapi/mkl.hpp> 

# Version
20241227

# Log
```
/.../onemkl_interfaces/20241227/include/oneapi/mkl.hpp:24:9: warning: Header `oneapi/mkl.hpp` is deprecated, please use `oneapi/math.hpp` instead [-W#pragma-messages]
   24 | #pragma message("Header `oneapi/mkl.hpp` is deprecated, please use `oneapi/math.hpp` instead")
      |         ^
/.../onemkl_interfaces/20241227/include/oneapi/mkl.hpp:34:10: fatal error: 'namespace_alias.hpp' file not found
   34 | #include "namespace_alias.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
```

### PR DESCRIPTION
**Pull request by Rbiessy**
# Description

Fix include path when using `mkl.hpp`. I have reproduced the issue with a small sample that uses `mkl.hpp`. This should fix the issue.

Fixes https://github.com/uxlfoundation/oneMath/issues/623

# Checklist

## All Submissions

- [N/A] Do all unit tests pass locally? (tests do not use mkl.hpp)

### CODE REVIEW

**Review by AD2605 — APPROVED** [review]

File: include/oneapi/mkl.hpp [hunk 1]
```diff
@@ -31,6 +31,6 @@
 #include "oneapi/math/rng.hpp"
 #include "oneapi/math/sparse_blas.hpp"
 
-#include "namespace_alias.hpp"
+#include "mkl/namespace_alias.hpp"
```
Comment (dnhsieh-intel) [inline include/oneapi/mkl.hpp:34]: Do we also need `oneapi` here, i.e., `oneapi/mkl/namespace_alias.hpp`? I didn't test it, just a quick check.

Comment (zhiweij1) [reply include/oneapi/mkl.hpp:34]: Hi @dnhsieh-intel, I tested both fixes; they work. `oneapi/mkl/namespace_alias.hpp` is relative to a path in `CPATH`, while `mkl/namespace_alias.hpp` is relative to the current file.

**Review by zhiweij1 — APPROVED** [review]

**Review by dnhsieh-intel — APPROVED** [review]
